language: python


python:
    - "3.5"

install:
    - pip install -r requirements.txt
    - pip install --user codecov

script:
    - python tests.py
    - coverage run tests.py


after_success:
    - codecov
